
const res = new Map();

    res.set("Overview", `<h2>Overview</h2> <p>In this project, we focus on the job searching application Linkedin. We wanted to see how useful the application is in helping fourth-years (or students in their last year of undergrad)  who are looking for a post-grad job. We recruited graduating students who were looking for a post-grad job. When interviewing our participants, our questions focused on how they used the app and what specific features they liked or disliked. We recognized the key aspects that make Linkedin popular such as finding a job, growing one's network, and connecting with recruiters. Based on this, we centered our interview to see which of these aspects were strong and what were the specific pain points. For our persona, we wanted our participants to be graduating as it's an important time for many to find a job for the upcoming year. We assumed a lot of people in their last year would be having a higher use of the app. In this report, we go through the step-by-step process of our analysis and the impact of the application to our selected persona</p> <button class="closeB" onclick="closeNotes()">Close</button>`)
    res.set("Recruiting" ,`<h2>Recruiting</h2><p>One thing that stood out to us when we were recruiting, was that students in STEM were more likely to be using LinkedIn for job searching than other majors. When we were looking for graduating students at UCI who are using LinkedIn to find jobs we saw a high number of students pursuing a job in a tech field. While our goal was to gain a comprehensive report of students of various backgrounds, we saw 4 out of 5 of our participants pursuing a job in a STEM-oriented field. When recruiting in the future, we would specify how each participant should be from a different field to gain a better understanding of how useful Linkedin is for overall graduating students. A way to specifically diversify who we interview is by finding a student per department, this way we can get a clearer picture of what each type of student thinks experience is using Linkedin instead of solely STEM majors because our goal would be to get insights of the apps use of all types of graduating students.</p><button class="closeB" onclick="closeNotes()">Close</button>`)
    res.set("Persona" ,`<h2>Persona</h2><p>Creating a persona taught us that representing a subpopulation of LinkedIn users in one persona can be challenging. From the interviews, we discovered that although there were similarities among users, each person had a unique perspective of the app. Creating a single persona from all the interviews brought up conflicting perspectives. For example, some participants felt that LinkedIn accurately showcased their skill set, while others believed their profiles only provided a basic overview of their abilities. Another lesson we learned was gaining a deeper understanding of users and their motivations. The process allows us to put ourselves in the user’s positions, allowing us to be more empathetic and help us see their experiences more clearly. One thing we would do differently next time is to define a more specific archetype when building the persona. For example, “fourth year college students actively looking for a job”, our subpopulation, is a but broad; narrowing it down to “high-achieving fourth year seeking top positions” versus  “fourth year who is unsure of their career path” would make a significant difference in how they might use the app. Overall, being more specific about the archetype would improve the clarity and focus of the persona.</p><button class="closeB" onclick="closeNotes()">Close</button>`)
    res.set("Interview", "After conducting each interview, we learned that it is much easier to have the scribe or interviewer actually audio recording the conversation in case the scribe is not able to capture everything the interviewee was saying. Additionally, we found it helpful for the interviewer to ask follow-up questions if the interviewee’s answers were very short or broad so that we were able to gain valuable insight and feedback. It is very important to cater the interview towards the user. Some users did not open up as fast or did not feel comfortable sharing many details in the first few questions of the interview, and so by structuring the interview questions the way we did it allowed the interviewee to gain more comfort and confidence by the time we asked the longer, more in-depth questions. This also allowed the interviewee to start thinking about their use and feelings about LinkedIn before directly asked. For future interviews, we would record each of the interviews on audio and then cross-check the recordings after with the notes taken by the scribe. We can then edit the notes taken to be sure that they include each point and even specific language that the user touched on so that the feedback is as specific as possible. In some cases, one charged word can change the entire meaning of a sentence, and so it is important that singular words are not missed because the interviewee is talking too fast or the scribe is not able to write fast enough. Additionally, it may be easier to take notes in bullet point form instead of full sentences in order to better organize general thoughts and ideas. This is also a quicker form of note taking for the scribe, and they should be able to capture each of the key/main ideas during the interview and then fill in anything they missed from the recording after. Last, even though we rotated interviewers and scribes, it may be helpful to have one consistent scribe for each of the interviews so that the notes are as consistent as possible. Since our interview questions were relatively simple this did not matter as much, but on a future project this could be another area for improvement.")
    res.set("Analysis",`<h2>Analysis</h2><p>After collecting responses for each interview question, our team discussed the similarities and differences of each interview, as well as the kinds of suggestions each interviewee gave that they thought could improve the quality of life or accessibility of LinkedIn. Along the way, we ran into problems that helped us gain a better understanding of how to make the analysis step smoother in the future. One of the first things we found out was that we needed to add or change some questions in order to properly get the information we were seeking. For example, after conducting a few interviews we noticed that we forgot to ask if the interviewee felt LinkedIn lacked a certain feature where a different app implements better. This took up some time which held up our progress when we started to analyze. We found out that in order to accurately obtain all the info we should have spent more time perfecting the interview questions. This way we can move straight into analysis after interviews. We also realized that conducting analysis as a group was far more productive than trying to do it separately. We realized that we all interpreted our interviews a little differently and bringing them up as a group assisted in keeping the team on the same page. Additionally, writing our analysis points on the FigJam helped us sort our ideas and group our thoughts together.</p><button class="closeB" onclick="closeNotes()">Close</button>`);
    res.set(
        "Users Frustration",
        `<h2>User Frustations</h2><ul><li>A user mentioned removing the limits to how many people they can search or message.</li><li> A user mentioned that they can get bombarded with opportunities that are just scams</li><li>A user mentioned how they are not able to turn off the automatic notification from the app.</li><li>While some of the job recommendations are appropriate, LinkedIn does not have a good filter/sort system.</li><li>A participant says using the job-search can be confusing and there should be an easier way to navigate through categories.</li></ul><button class="closeB" onclick="closeNotes()">Close</button>`
    )
    res.set("Quotes",`<h2>Quotes</h2><h3>"I do think that i am a target user for linkedin because i am an undergraduate student who is interested in professional networking & occupational opportunities, which is what most of their features revolve around."</h3><h3>"It’s comparable to other platforms, but I find Glassdoor’s Q&A section very helpful. The reviews and ratings from applicants and current/former employees provide valuable information on the company and help me decide if I want to apply for the company or not."</h3> <h3>"I do think that I am a target user for LinkedIn because I am an undergraduate student who is interested in professional networking & occupational opportunities, which is what most of their features revolve around"</h3> <h3>"I don’t think that LinkedIn contributed much to preparing me for the current job market because I have had previous & current professional experiences which have given me a better understanding of the industry & the skills required for most positions. LinkedIn is useful for networking but a hands-on work experience & personal mentorship from my supervisors have been more effective in preparing me to be proficient for the real-world challenges I will encounter."</h3> <h3>"Yes I believe my LinkedIn profile properly conveys my skillset to my employers, but I think my resume is better for that because with a resume I get to decide the layout and how I want to present the information."</h3> <h3>"I would say because LinkedIn is so social media focused, it lacks in actually finding jobs. So it’s almost like more of a social media platform than an actual job seeking platform."</h3> <button class="closeB" onclick="closeNotes()">Close</button>`)
    res.set("Goals",`<ul><h3>LinkedIn User Goals</h3> <li>A User had stated that LinkedIn is missing a rate and review feature for companies that is similar to the one on the application Glassdoor, Users want to be able to use LinkedIn as a way to not just find out about apps but to look at experience employees have with that company so they can see if its a good fit for their interest </li> <li>A User suggested that LinkedIn host workshops and networking events to promote the use of their app and to teach users how to effectively use their application to network</li> <li>Users typically believed that LinkedIn accurately potrayed their skills and their profile was something that they could share to employers as a method to help convey their qualifications</li> <li>Users have difficulty finding opportunities in general and want to connect with as many people as they can but the restrictions for how many people they can message can be detrimental to them</li> </ul> <button class="closeB" onclick="closeNotes()">Close</button>`)
    res.set("Motivation",`<ul><h3>These are the most prominent motivations we noted from Users for using LinkedIn</h3> <li>We noticed that some users enjoyed using the application to view the requirements for positions they want to have althought the requirements are not always accurate to what is necessary for the job</li> <li>Users felt that the application was useful to find companies and positions but felt it was better to go to career pages of those companies to apply instead because they didnt have much luck applying directly on Linked In </li> <li>Users typically believed that LinkedIn accurately potrayed their skills and their profile was something that they could share to employers as a method to help convey their qualifications</li> <li>Although users dont have much luck applying directly on linked in they still feel its necessary to have one to keep up with companies and events that could help them</li> </ul> <button class="closeB" onclick="closeNotes()">Close</button>`)
function openNotes(text) {
    document.getElementById('Notepad').style.display = 'flex';
    document.querySelector('div.note-content').innerHTML = res.get(text);

}

function closeNotes() {
    document.getElementById('Notepad').style.display = 'none';
}

window.onclick = function(event) {
    var notes = document.getElementById('myNotes');
    if (event.target === notes) {
        closeNotes();
    }
}


/* motives

Users typically only put job experience on their profiles.


*/

/* goals

Users typically only put job experience on their profiles.


*/

/* motives

Users typically only put job experience on their profiles.


*/

